apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa-tiller
  namespace: demo-app
-----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-crb-tiller
  namespace: demo-app
subjects:
- kind: ServiceAccount
  name: app-sa-tiller
  namespace: demo-app
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io